---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - podinfo/dev/app/podinfo.yaml
  - podinfo/dev/project.yaml
  - podinfo/prod/app/podinfo.yaml
  - podinfo/prod/project.yaml
